require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/Documentation:
  Enabled: false
