require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/support/mocks/**/*'

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods:
    - describe
  Exclude:
    - 'spec/support/mocks/**/*'

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5
