name: RSpec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Install PostgreSQL
        run: sudo apt-get -yqq install libpq-dev
      - name: Install Bundler
        run: gem install bundler
      - name: Run bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Setup DB
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: bin/rails db:create db:schema:load
      - name: Run RSpec
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          RAILS_MASTER_KEY: 2df7c389ef1d34a0703bea91c8096d55
          BINANCE_TLD: US
        run: bundle exec rspec
